# nixpacks.toml

[phases.install]
cmds = [
  "npm install",
  "cd apps/mufl && npm install",
  "cd apps/threads && npm install"
]

[phases.build]
cmds = [
  "cd apps/mufl && npm run build",
  "cd apps/threads && npm run build"
]

[start]
cmd = "node server.js"
